### PR TITLE
Adding support for Misaka 2.

### PR DESCRIPTION
**Pull request by flamusdiu**
I fixed all tests but `test_inverse_render` keeps failing. This is probably due to the API change, but I am not sure why it's failing at the moment.

### CODE REVIEW

**Comment by singingwolfboy** [comment]
Thanks for doing this, @flamusdiu! I'm OK with deleting that one failing test -- you're right that the API has changed, so I believe that the test is no longer valid. Could you do the following things, and then I'll merge the pull request?

* Delete the failing test, so that the build passes
* Indicate in the `setup.py` file that `flask-misaka` now requires version 2.X of the `misaka` module. I believe it's going to be `install_requires=['Flask>=0.7', 'misaka>=2.0<3.0']`
* Update the `docs/index.rst` file to indicate which options are now available. I looks to me like some have been removed, and others have probably been added.
* Add an `AUTHORS` file giving yourself credit for the awesome work you've done!

Let me know if you want any help with this. For example, I'm happy to update the documentation for you if you point me to some kind of changelog or documentation for Misaka that shows what has changed.

Once this merges, I'll cut a new release of Flask-Misaka shortly thereafter and push it to PyPI. The only other change I want to make is changing the tests to use [pytest](http://pytest.org) instead of nose, but I can do that in a separate pull request.

Thanks again for all your amazing help!

**Comment by flamusdiu** [comment]
@singingwolfboy Changelog: http://misaka.61924.nl/changelog.html

**Comment by flamusdiu** [comment]
@singingwolfboy looks like coverage is failing now. Not sure if that will be fixed when you rewrite the tests for `pytest` or not. 

I am reworking the doc here: https://github.com/flamusdiu/flask-misaka/pull/1 

I need to do some testing to make sure I add the proper information. Also, `Smartypants` was changed to a function: `misaka.smartypants()` instead of a EXT.

**Comment by singingwolfboy** [comment]
I fixed the coverage issue in https://github.com/flamusdiu/flask-misaka/pull/2. You should be able to just merge it, and that will update *this* pull request.

**Comment by flamusdiu** [comment]
Nope, still missing that one line of code.

**Comment by singingwolfboy** [comment]
Huh. Well, I think this is ready to merge, and I'll see if I can clean up that coverage issue in a future pull request. Thanks again, @flamusdiu!

**Comment by flamusdiu** [comment]
Thanks! =)

**Comment by flamusdiu** [comment]
This closes issues/11

**Pull request merged**
